spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=qqjx mdve wrdc rwak
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
twilio.accountSid=YOUR_TWILIO_SID
twilio.authToken=YOUR_TWILIO_TOKEN
twilio.from.number=YOUR_NUMBER